[package]
name = "ex_pdf_to_text"
version = "0.0.1"
authors = []
edition = "2021"

[lib]
name = "ex_pdf_to_text"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
poppler-rs = "0.19.0"
